---
version: '3.8'
services:
  backend:
    build: ./es_backend
    ports:
     - 5001:5001
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5002:5432'
    volumes: 
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local